export { default as HomePage } from './HomePage';
export { default as ShopPage } from './ShopPage';
export { default as BlogPage } from './BlogPage';
export { default as ContactPage } from './ContactPage';
export { default as CheckoutPage } from './CheckoutPage';
export { default as CartPage } from './CartPage';
export {default as SingleProductPage } from './SingleProductPage';
export { default as SingleBlogPage } from './SingleBlogPage';
export { default as LoginPage } from './LoginPage';
export { default as RegisterPage } from './RegisterPage';
export { default as ProfilePage } from './ProfilePage';